package polity

import "github.com/Rioverde/gongeons/internal/game/geom"

// Camp is a pre-historic settler cluster — the seed input to the 200-year
// fold-forward simulation. Each camp occupies 2-3 connected tiles (footprint)
// and inherits a RegionCharacter from its anchor tile's super-chunk. Population
// ranges from 10-50; all camps are founded at simulation start (year 0).
// Survivors of the simulation are promoted to Hamlet or Village; non-survivors
// are retired.
type Camp struct {
	Settlement
}

// Base returns a pointer to the embedded Settlement, satisfying the Place
// interface.
func (c *Camp) Base() *Settlement { return &c.Settlement }

// CampSource is the consumer-side interface the simulation delegates to when
// reading the initial camp distribution generated by worldgen. The interface
// lives in this package because the simulation tier consumes it — per Go
// interface-design guidance, interfaces belong at the consumer.
//
// Implementations must be deterministic: the same SuperChunkCoord yields the
// same []Camp every call (including order), and must be safe for concurrent
// read. Returning nil or an empty slice signals "no camps in this
// super-chunk". All() returns the full sorted list for diagnostics, dev
// tools, and tests.
type CampSource interface {
	CampsIn(sc geom.SuperChunkCoord) []Camp
	All() []Camp
}
