// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gongeons.proto

package gongeonspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Terrain is the biome of a tile. One value per domain terrain, so the
// client can render every biome distinctly without asking the server for
// side-channel info.
type Terrain int32

const (
	Terrain_TERRAIN_UNSPECIFIED Terrain = 0
	Terrain_TERRAIN_PLAINS      Terrain = 1
	Terrain_TERRAIN_GRASSLAND   Terrain = 2
	Terrain_TERRAIN_MEADOW      Terrain = 3
	Terrain_TERRAIN_BEACH       Terrain = 4
	Terrain_TERRAIN_DESERT      Terrain = 5
	Terrain_TERRAIN_SAVANNA     Terrain = 6
	Terrain_TERRAIN_FOREST      Terrain = 7
	Terrain_TERRAIN_JUNGLE      Terrain = 8
	Terrain_TERRAIN_TAIGA       Terrain = 9
	Terrain_TERRAIN_TUNDRA      Terrain = 10
	Terrain_TERRAIN_SNOW        Terrain = 11
	Terrain_TERRAIN_HILLS       Terrain = 12
	Terrain_TERRAIN_MOUNTAIN    Terrain = 13
	Terrain_TERRAIN_SNOWY_PEAK  Terrain = 14
	Terrain_TERRAIN_OCEAN       Terrain = 15
	Terrain_TERRAIN_DEEP_OCEAN  Terrain = 16
)

// Enum value maps for Terrain.
var (
	Terrain_name = map[int32]string{
		0:  "TERRAIN_UNSPECIFIED",
		1:  "TERRAIN_PLAINS",
		2:  "TERRAIN_GRASSLAND",
		3:  "TERRAIN_MEADOW",
		4:  "TERRAIN_BEACH",
		5:  "TERRAIN_DESERT",
		6:  "TERRAIN_SAVANNA",
		7:  "TERRAIN_FOREST",
		8:  "TERRAIN_JUNGLE",
		9:  "TERRAIN_TAIGA",
		10: "TERRAIN_TUNDRA",
		11: "TERRAIN_SNOW",
		12: "TERRAIN_HILLS",
		13: "TERRAIN_MOUNTAIN",
		14: "TERRAIN_SNOWY_PEAK",
		15: "TERRAIN_OCEAN",
		16: "TERRAIN_DEEP_OCEAN",
	}
	Terrain_value = map[string]int32{
		"TERRAIN_UNSPECIFIED": 0,
		"TERRAIN_PLAINS":      1,
		"TERRAIN_GRASSLAND":   2,
		"TERRAIN_MEADOW":      3,
		"TERRAIN_BEACH":       4,
		"TERRAIN_DESERT":      5,
		"TERRAIN_SAVANNA":     6,
		"TERRAIN_FOREST":      7,
		"TERRAIN_JUNGLE":      8,
		"TERRAIN_TAIGA":       9,
		"TERRAIN_TUNDRA":      10,
		"TERRAIN_SNOW":        11,
		"TERRAIN_HILLS":       12,
		"TERRAIN_MOUNTAIN":    13,
		"TERRAIN_SNOWY_PEAK":  14,
		"TERRAIN_OCEAN":       15,
		"TERRAIN_DEEP_OCEAN":  16,
	}
)

func (x Terrain) Enum() *Terrain {
	p := new(Terrain)
	*p = x
	return p
}

func (x Terrain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Terrain) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[0].Descriptor()
}

func (Terrain) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[0]
}

func (x Terrain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Terrain.Descriptor instead.
func (Terrain) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{0}
}

// OccupantKind distinguishes entities on a tile. OCCUPANT_MONSTER is reserved
// for future gameplay work — the current MVP only uses OCCUPANT_PLAYER.
type OccupantKind int32

const (
	OccupantKind_OCCUPANT_UNSPECIFIED OccupantKind = 0
	OccupantKind_OCCUPANT_PLAYER      OccupantKind = 1
	OccupantKind_OCCUPANT_MONSTER     OccupantKind = 2
)

// Enum value maps for OccupantKind.
var (
	OccupantKind_name = map[int32]string{
		0: "OCCUPANT_UNSPECIFIED",
		1: "OCCUPANT_PLAYER",
		2: "OCCUPANT_MONSTER",
	}
	OccupantKind_value = map[string]int32{
		"OCCUPANT_UNSPECIFIED": 0,
		"OCCUPANT_PLAYER":      1,
		"OCCUPANT_MONSTER":     2,
	}
)

func (x OccupantKind) Enum() *OccupantKind {
	p := new(OccupantKind)
	*p = x
	return p
}

func (x OccupantKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OccupantKind) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[1].Descriptor()
}

func (OccupantKind) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[1]
}

func (x OccupantKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OccupantKind.Descriptor instead.
func (OccupantKind) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{1}
}

// Structure is a single built feature on a tile — mutually exclusive.
// Binary overlay features (river, road, bridge...) go in Tile.overlays.
type Structure int32

const (
	Structure_STRUCTURE_UNSPECIFIED Structure = 0
	Structure_STRUCTURE_VILLAGE     Structure = 1
	Structure_STRUCTURE_CASTLE      Structure = 2
)

// Enum value maps for Structure.
var (
	Structure_name = map[int32]string{
		0: "STRUCTURE_UNSPECIFIED",
		1: "STRUCTURE_VILLAGE",
		2: "STRUCTURE_CASTLE",
	}
	Structure_value = map[string]int32{
		"STRUCTURE_UNSPECIFIED": 0,
		"STRUCTURE_VILLAGE":     1,
		"STRUCTURE_CASTLE":      2,
	}
)

func (x Structure) Enum() *Structure {
	p := new(Structure)
	*p = x
	return p
}

func (x Structure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Structure) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[2].Descriptor()
}

func (Structure) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[2]
}

func (x Structure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Structure.Descriptor instead.
func (Structure) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{2}
}

// Position is an absolute square-grid tile coordinate. Origin is arbitrary
// (world 0, 0); the coordinate system is unbounded in both axes.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_gongeons_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Tile is an atomic map cell. Used in Snapshot only — Events carry deltas,
// not full tile replacements. overlays is a bitmask of TileOverlay flag
// values shared with the domain (river, road, bridge, path...).
type Tile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Terrain       Terrain                `protobuf:"varint,1,opt,name=terrain,proto3,enum=gongeons.v1.Terrain" json:"terrain,omitempty"`
	Occupant      OccupantKind           `protobuf:"varint,2,opt,name=occupant,proto3,enum=gongeons.v1.OccupantKind" json:"occupant,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`               // occupant ID, empty if no occupant
	Overlays      uint32                 `protobuf:"varint,4,opt,name=overlays,proto3" json:"overlays,omitempty"`                              // bitmask of TileOverlay flag values
	Structure     Structure              `protobuf:"varint,5,opt,name=structure,proto3,enum=gongeons.v1.Structure" json:"structure,omitempty"` // village / castle overlay
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_gongeons_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{1}
}

func (x *Tile) GetTerrain() Terrain {
	if x != nil {
		return x.Terrain
	}
	return Terrain_TERRAIN_UNSPECIFIED
}

func (x *Tile) GetOccupant() OccupantKind {
	if x != nil {
		return x.Occupant
	}
	return OccupantKind_OCCUPANT_UNSPECIFIED
}

func (x *Tile) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Tile) GetOverlays() uint32 {
	if x != nil {
		return x.Overlays
	}
	return 0
}

func (x *Tile) GetStructure() Structure {
	if x != nil {
		return x.Structure
	}
	return Structure_STRUCTURE_UNSPECIFIED
}

// Entity is a positioned actor in the world. Combat stats / monsters are
// added in a later phase on top of this shape.
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          OccupantKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=gongeons.v1.OccupantKind" json:"kind,omitempty"`
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_gongeons_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetKind() OccupantKind {
	if x != nil {
		return x.Kind
	}
	return OccupantKind_OCCUPANT_UNSPECIFIED
}

func (x *Entity) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Move
	//	*ClientMessage_Viewport
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_gongeons_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{3}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetMove() *MoveCmd {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *ClientMessage) GetViewport() *ViewportCmd {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Viewport); ok {
			return x.Viewport
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Join struct {
	Join *JoinRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_Move struct {
	Move *MoveCmd `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type ClientMessage_Viewport struct {
	Viewport *ViewportCmd `protobuf:"bytes,3,opt,name=viewport,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Payload() {}

func (*ClientMessage_Move) isClientMessage_Payload() {}

func (*ClientMessage_Viewport) isClientMessage_Payload() {}

// JoinRequest is the first message a client sends. The server assigns a
// PlayerID in JoinAccepted and begins broadcasting events to this stream.
// viewport_width and viewport_height are the desired Snapshot dimensions
// for this client; zero means "use server defaults".
type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ViewportWidth  int32                  `protobuf:"varint,2,opt,name=viewport_width,json=viewportWidth,proto3" json:"viewport_width,omitempty"`
	ViewportHeight int32                  `protobuf:"varint,3,opt,name=viewport_height,json=viewportHeight,proto3" json:"viewport_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_gongeons_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinRequest) GetViewportWidth() int32 {
	if x != nil {
		return x.ViewportWidth
	}
	return 0
}

func (x *JoinRequest) GetViewportHeight() int32 {
	if x != nil {
		return x.ViewportHeight
	}
	return 0
}

// ViewportCmd updates the Snapshot dimensions the server should use for
// this client — the terminal resized, we want a bigger / smaller view.
// The server replies with a fresh Snapshot at the new size.
type ViewportCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewportCmd) Reset() {
	*x = ViewportCmd{}
	mi := &file_gongeons_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportCmd) ProtoMessage() {}

func (x *ViewportCmd) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportCmd.ProtoReflect.Descriptor instead.
func (*ViewportCmd) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{5}
}

func (x *ViewportCmd) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ViewportCmd) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// MoveCmd asks to move one step. dx/dy are in {-1, 0, 1}; exactly one is
// non-zero (four-directional movement via WASD).
type MoveCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dx            int32                  `protobuf:"varint,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,2,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCmd) Reset() {
	*x = MoveCmd{}
	mi := &file_gongeons_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCmd) ProtoMessage() {}

func (x *MoveCmd) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCmd.ProtoReflect.Descriptor instead.
func (*MoveCmd) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{6}
}

func (x *MoveCmd) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *MoveCmd) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Accepted
	//	*ServerMessage_Snapshot
	//	*ServerMessage_Event
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_gongeons_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAccepted() *JoinAccepted {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *ServerMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ServerMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Accepted struct {
	Accepted *JoinAccepted `protobuf:"bytes,1,opt,name=accepted,proto3,oneof"`
}

type ServerMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type ServerMessage_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Accepted) isServerMessage_Payload() {}

func (*ServerMessage_Snapshot) isServerMessage_Payload() {}

func (*ServerMessage_Event) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

// JoinAccepted is the server's reply to JoinRequest. It carries the generated
// PlayerID and the player's spawn position — the client stores the ID and
// uses it to recognise its own events.
type JoinAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Spawn         *Position              `protobuf:"bytes,2,opt,name=spawn,proto3" json:"spawn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAccepted) Reset() {
	*x = JoinAccepted{}
	mi := &file_gongeons_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAccepted) ProtoMessage() {}

func (x *JoinAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAccepted.ProtoReflect.Descriptor instead.
func (*JoinAccepted) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{8}
}

func (x *JoinAccepted) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinAccepted) GetSpawn() *Position {
	if x != nil {
		return x.Spawn
	}
	return nil
}

// Snapshot is a viewport of the world. Width/height are tile counts; origin
// is the world-space position of the top-left tile. Tiles are row-major of
// length width*height.
type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Origin        *Position              `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Tiles         []*Tile                `protobuf:"bytes,4,rep,name=tiles,proto3" json:"tiles,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_gongeons_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{9}
}

func (x *Snapshot) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Snapshot) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Snapshot) GetOrigin() *Position {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Snapshot) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *Snapshot) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

// Event is a domain event the server broadcasts to every connected client.
// The client applies it to its local Model to stay in sync.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_PlayerJoined
	//	*Event_PlayerLeft
	//	*Event_EntityMoved
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_gongeons_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{10}
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Payload.(*Event_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *Event) GetPlayerLeft() *PlayerLeft {
	if x != nil {
		if x, ok := x.Payload.(*Event_PlayerLeft); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *Event) GetEntityMoved() *EntityMoved {
	if x != nil {
		if x, ok := x.Payload.(*Event_EntityMoved); ok {
			return x.EntityMoved
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,1,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type Event_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,2,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

type Event_EntityMoved struct {
	EntityMoved *EntityMoved `protobuf:"bytes,3,opt,name=entity_moved,json=entityMoved,proto3,oneof"`
}

func (*Event_PlayerJoined) isEvent_Payload() {}

func (*Event_PlayerLeft) isEvent_Payload() {}

func (*Event_EntityMoved) isEvent_Payload() {}

type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_gongeons_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerJoined) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type PlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	mi := &file_gongeons_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerLeft) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type EntityMoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	From          *Position              `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Position              `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMoved) Reset() {
	*x = EntityMoved{}
	mi := &file_gongeons_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMoved) ProtoMessage() {}

func (x *EntityMoved) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMoved.ProtoReflect.Descriptor instead.
func (*EntityMoved) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{13}
}

func (x *EntityMoved) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityMoved) GetFrom() *Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EntityMoved) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_gongeons_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{14}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_gongeons_proto protoreflect.FileDescriptor

const file_gongeons_proto_rawDesc = "" +
	"\n" +
	"\x0egongeons.proto\x12\vgongeons.v1\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xdc\x01\n" +
	"\x04Tile\x12.\n" +
	"\aterrain\x18\x01 \x01(\x0e2\x14.gongeons.v1.TerrainR\aterrain\x125\n" +
	"\boccupant\x18\x02 \x01(\x0e2\x19.gongeons.v1.OccupantKindR\boccupant\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1a\n" +
	"\boverlays\x18\x04 \x01(\rR\boverlays\x124\n" +
	"\tstructure\x18\x05 \x01(\x0e2\x16.gongeons.v1.StructureR\tstructure\"\x8e\x01\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x19.gongeons.v1.OccupantKindR\x04kind\x121\n" +
	"\bposition\x18\x04 \x01(\v2\x15.gongeons.v1.PositionR\bposition\"\xae\x01\n" +
	"\rClientMessage\x12.\n" +
	"\x04join\x18\x01 \x01(\v2\x18.gongeons.v1.JoinRequestH\x00R\x04join\x12*\n" +
	"\x04move\x18\x02 \x01(\v2\x14.gongeons.v1.MoveCmdH\x00R\x04move\x126\n" +
	"\bviewport\x18\x03 \x01(\v2\x18.gongeons.v1.ViewportCmdH\x00R\bviewportB\t\n" +
	"\apayload\"q\n" +
	"\vJoinRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eviewport_width\x18\x02 \x01(\x05R\rviewportWidth\x12'\n" +
	"\x0fviewport_height\x18\x03 \x01(\x05R\x0eviewportHeight\";\n" +
	"\vViewportCmd\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\")\n" +
	"\aMoveCmd\x12\x0e\n" +
	"\x02dx\x18\x01 \x01(\x05R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x02 \x01(\x05R\x02dy\"\xe8\x01\n" +
	"\rServerMessage\x127\n" +
	"\baccepted\x18\x01 \x01(\v2\x19.gongeons.v1.JoinAcceptedH\x00R\baccepted\x123\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x15.gongeons.v1.SnapshotH\x00R\bsnapshot\x12*\n" +
	"\x05event\x18\x03 \x01(\v2\x12.gongeons.v1.EventH\x00R\x05event\x122\n" +
	"\x05error\x18\x04 \x01(\v2\x1a.gongeons.v1.ErrorResponseH\x00R\x05errorB\t\n" +
	"\apayload\"X\n" +
	"\fJoinAccepted\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05spawn\x18\x02 \x01(\v2\x15.gongeons.v1.PositionR\x05spawn\"\xc1\x01\n" +
	"\bSnapshot\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12-\n" +
	"\x06origin\x18\x03 \x01(\v2\x15.gongeons.v1.PositionR\x06origin\x12'\n" +
	"\x05tiles\x18\x04 \x03(\v2\x11.gongeons.v1.TileR\x05tiles\x12/\n" +
	"\bentities\x18\x05 \x03(\v2\x13.gongeons.v1.EntityR\bentities\"\xcf\x01\n" +
	"\x05Event\x12@\n" +
	"\rplayer_joined\x18\x01 \x01(\v2\x19.gongeons.v1.PlayerJoinedH\x00R\fplayerJoined\x12:\n" +
	"\vplayer_left\x18\x02 \x01(\v2\x17.gongeons.v1.PlayerLeftH\x00R\n" +
	"playerLeft\x12=\n" +
	"\fentity_moved\x18\x03 \x01(\v2\x18.gongeons.v1.EntityMovedH\x00R\ventityMovedB\t\n" +
	"\apayload\";\n" +
	"\fPlayerJoined\x12+\n" +
	"\x06entity\x18\x01 \x01(\v2\x13.gongeons.v1.EntityR\x06entity\")\n" +
	"\n" +
	"PlayerLeft\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"|\n" +
	"\vEntityMoved\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12)\n" +
	"\x04from\x18\x02 \x01(\v2\x15.gongeons.v1.PositionR\x04from\x12%\n" +
	"\x02to\x18\x03 \x01(\v2\x15.gongeons.v1.PositionR\x02to\"=\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code*\xea\x02\n" +
	"\aTerrain\x12\x17\n" +
	"\x13TERRAIN_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTERRAIN_PLAINS\x10\x01\x12\x15\n" +
	"\x11TERRAIN_GRASSLAND\x10\x02\x12\x12\n" +
	"\x0eTERRAIN_MEADOW\x10\x03\x12\x11\n" +
	"\rTERRAIN_BEACH\x10\x04\x12\x12\n" +
	"\x0eTERRAIN_DESERT\x10\x05\x12\x13\n" +
	"\x0fTERRAIN_SAVANNA\x10\x06\x12\x12\n" +
	"\x0eTERRAIN_FOREST\x10\a\x12\x12\n" +
	"\x0eTERRAIN_JUNGLE\x10\b\x12\x11\n" +
	"\rTERRAIN_TAIGA\x10\t\x12\x12\n" +
	"\x0eTERRAIN_TUNDRA\x10\n" +
	"\x12\x10\n" +
	"\fTERRAIN_SNOW\x10\v\x12\x11\n" +
	"\rTERRAIN_HILLS\x10\f\x12\x14\n" +
	"\x10TERRAIN_MOUNTAIN\x10\r\x12\x16\n" +
	"\x12TERRAIN_SNOWY_PEAK\x10\x0e\x12\x11\n" +
	"\rTERRAIN_OCEAN\x10\x0f\x12\x16\n" +
	"\x12TERRAIN_DEEP_OCEAN\x10\x10*S\n" +
	"\fOccupantKind\x12\x18\n" +
	"\x14OCCUPANT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOCCUPANT_PLAYER\x10\x01\x12\x14\n" +
	"\x10OCCUPANT_MONSTER\x10\x02*S\n" +
	"\tStructure\x12\x19\n" +
	"\x15STRUCTURE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STRUCTURE_VILLAGE\x10\x01\x12\x14\n" +
	"\x10STRUCTURE_CASTLE\x10\x022Q\n" +
	"\vGameService\x12B\n" +
	"\x04Play\x12\x1a.gongeons.v1.ClientMessage\x1a\x1a.gongeons.v1.ServerMessage(\x010\x01B8Z6github.com/Rioverde/gongeons/internal/proto;gongeonspbb\x06proto3"

var (
	file_gongeons_proto_rawDescOnce sync.Once
	file_gongeons_proto_rawDescData []byte
)

func file_gongeons_proto_rawDescGZIP() []byte {
	file_gongeons_proto_rawDescOnce.Do(func() {
		file_gongeons_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gongeons_proto_rawDesc), len(file_gongeons_proto_rawDesc)))
	})
	return file_gongeons_proto_rawDescData
}

var file_gongeons_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gongeons_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_gongeons_proto_goTypes = []any{
	(Terrain)(0),          // 0: gongeons.v1.Terrain
	(OccupantKind)(0),     // 1: gongeons.v1.OccupantKind
	(Structure)(0),        // 2: gongeons.v1.Structure
	(*Position)(nil),      // 3: gongeons.v1.Position
	(*Tile)(nil),          // 4: gongeons.v1.Tile
	(*Entity)(nil),        // 5: gongeons.v1.Entity
	(*ClientMessage)(nil), // 6: gongeons.v1.ClientMessage
	(*JoinRequest)(nil),   // 7: gongeons.v1.JoinRequest
	(*ViewportCmd)(nil),   // 8: gongeons.v1.ViewportCmd
	(*MoveCmd)(nil),       // 9: gongeons.v1.MoveCmd
	(*ServerMessage)(nil), // 10: gongeons.v1.ServerMessage
	(*JoinAccepted)(nil),  // 11: gongeons.v1.JoinAccepted
	(*Snapshot)(nil),      // 12: gongeons.v1.Snapshot
	(*Event)(nil),         // 13: gongeons.v1.Event
	(*PlayerJoined)(nil),  // 14: gongeons.v1.PlayerJoined
	(*PlayerLeft)(nil),    // 15: gongeons.v1.PlayerLeft
	(*EntityMoved)(nil),   // 16: gongeons.v1.EntityMoved
	(*ErrorResponse)(nil), // 17: gongeons.v1.ErrorResponse
}
var file_gongeons_proto_depIdxs = []int32{
	0,  // 0: gongeons.v1.Tile.terrain:type_name -> gongeons.v1.Terrain
	1,  // 1: gongeons.v1.Tile.occupant:type_name -> gongeons.v1.OccupantKind
	2,  // 2: gongeons.v1.Tile.structure:type_name -> gongeons.v1.Structure
	1,  // 3: gongeons.v1.Entity.kind:type_name -> gongeons.v1.OccupantKind
	3,  // 4: gongeons.v1.Entity.position:type_name -> gongeons.v1.Position
	7,  // 5: gongeons.v1.ClientMessage.join:type_name -> gongeons.v1.JoinRequest
	9,  // 6: gongeons.v1.ClientMessage.move:type_name -> gongeons.v1.MoveCmd
	8,  // 7: gongeons.v1.ClientMessage.viewport:type_name -> gongeons.v1.ViewportCmd
	11, // 8: gongeons.v1.ServerMessage.accepted:type_name -> gongeons.v1.JoinAccepted
	12, // 9: gongeons.v1.ServerMessage.snapshot:type_name -> gongeons.v1.Snapshot
	13, // 10: gongeons.v1.ServerMessage.event:type_name -> gongeons.v1.Event
	17, // 11: gongeons.v1.ServerMessage.error:type_name -> gongeons.v1.ErrorResponse
	3,  // 12: gongeons.v1.JoinAccepted.spawn:type_name -> gongeons.v1.Position
	3,  // 13: gongeons.v1.Snapshot.origin:type_name -> gongeons.v1.Position
	4,  // 14: gongeons.v1.Snapshot.tiles:type_name -> gongeons.v1.Tile
	5,  // 15: gongeons.v1.Snapshot.entities:type_name -> gongeons.v1.Entity
	14, // 16: gongeons.v1.Event.player_joined:type_name -> gongeons.v1.PlayerJoined
	15, // 17: gongeons.v1.Event.player_left:type_name -> gongeons.v1.PlayerLeft
	16, // 18: gongeons.v1.Event.entity_moved:type_name -> gongeons.v1.EntityMoved
	5,  // 19: gongeons.v1.PlayerJoined.entity:type_name -> gongeons.v1.Entity
	3,  // 20: gongeons.v1.EntityMoved.from:type_name -> gongeons.v1.Position
	3,  // 21: gongeons.v1.EntityMoved.to:type_name -> gongeons.v1.Position
	6,  // 22: gongeons.v1.GameService.Play:input_type -> gongeons.v1.ClientMessage
	10, // 23: gongeons.v1.GameService.Play:output_type -> gongeons.v1.ServerMessage
	23, // [23:24] is the sub-list for method output_type
	22, // [22:23] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_gongeons_proto_init() }
func file_gongeons_proto_init() {
	if File_gongeons_proto != nil {
		return
	}
	file_gongeons_proto_msgTypes[3].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Move)(nil),
		(*ClientMessage_Viewport)(nil),
	}
	file_gongeons_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_Accepted)(nil),
		(*ServerMessage_Snapshot)(nil),
		(*ServerMessage_Event)(nil),
		(*ServerMessage_Error)(nil),
	}
	file_gongeons_proto_msgTypes[10].OneofWrappers = []any{
		(*Event_PlayerJoined)(nil),
		(*Event_PlayerLeft)(nil),
		(*Event_EntityMoved)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gongeons_proto_rawDesc), len(file_gongeons_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gongeons_proto_goTypes,
		DependencyIndexes: file_gongeons_proto_depIdxs,
		EnumInfos:         file_gongeons_proto_enumTypes,
		MessageInfos:      file_gongeons_proto_msgTypes,
	}.Build()
	File_gongeons_proto = out.File
	file_gongeons_proto_goTypes = nil
	file_gongeons_proto_depIdxs = nil
}
