// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: gongeons.proto

package gongeonspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Terrain is the biome of a tile. One value per domain terrain, so the
// client can render every biome distinctly without asking the server for
// side-channel info.
type Terrain int32

const (
	Terrain_TERRAIN_UNSPECIFIED Terrain = 0
	Terrain_TERRAIN_PLAINS      Terrain = 1
	Terrain_TERRAIN_GRASSLAND   Terrain = 2
	Terrain_TERRAIN_MEADOW      Terrain = 3
	Terrain_TERRAIN_BEACH       Terrain = 4
	Terrain_TERRAIN_DESERT      Terrain = 5
	Terrain_TERRAIN_SAVANNA     Terrain = 6
	Terrain_TERRAIN_FOREST      Terrain = 7
	Terrain_TERRAIN_JUNGLE      Terrain = 8
	Terrain_TERRAIN_TAIGA       Terrain = 9
	Terrain_TERRAIN_TUNDRA      Terrain = 10
	Terrain_TERRAIN_SNOW        Terrain = 11
	Terrain_TERRAIN_HILLS       Terrain = 12
	Terrain_TERRAIN_MOUNTAIN    Terrain = 13
	Terrain_TERRAIN_SNOWY_PEAK  Terrain = 14
	Terrain_TERRAIN_OCEAN       Terrain = 15
	Terrain_TERRAIN_DEEP_OCEAN  Terrain = 16
)

// Enum value maps for Terrain.
var (
	Terrain_name = map[int32]string{
		0:  "TERRAIN_UNSPECIFIED",
		1:  "TERRAIN_PLAINS",
		2:  "TERRAIN_GRASSLAND",
		3:  "TERRAIN_MEADOW",
		4:  "TERRAIN_BEACH",
		5:  "TERRAIN_DESERT",
		6:  "TERRAIN_SAVANNA",
		7:  "TERRAIN_FOREST",
		8:  "TERRAIN_JUNGLE",
		9:  "TERRAIN_TAIGA",
		10: "TERRAIN_TUNDRA",
		11: "TERRAIN_SNOW",
		12: "TERRAIN_HILLS",
		13: "TERRAIN_MOUNTAIN",
		14: "TERRAIN_SNOWY_PEAK",
		15: "TERRAIN_OCEAN",
		16: "TERRAIN_DEEP_OCEAN",
	}
	Terrain_value = map[string]int32{
		"TERRAIN_UNSPECIFIED": 0,
		"TERRAIN_PLAINS":      1,
		"TERRAIN_GRASSLAND":   2,
		"TERRAIN_MEADOW":      3,
		"TERRAIN_BEACH":       4,
		"TERRAIN_DESERT":      5,
		"TERRAIN_SAVANNA":     6,
		"TERRAIN_FOREST":      7,
		"TERRAIN_JUNGLE":      8,
		"TERRAIN_TAIGA":       9,
		"TERRAIN_TUNDRA":      10,
		"TERRAIN_SNOW":        11,
		"TERRAIN_HILLS":       12,
		"TERRAIN_MOUNTAIN":    13,
		"TERRAIN_SNOWY_PEAK":  14,
		"TERRAIN_OCEAN":       15,
		"TERRAIN_DEEP_OCEAN":  16,
	}
)

func (x Terrain) Enum() *Terrain {
	p := new(Terrain)
	*p = x
	return p
}

func (x Terrain) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Terrain) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[0].Descriptor()
}

func (Terrain) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[0]
}

func (x Terrain) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Terrain.Descriptor instead.
func (Terrain) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{0}
}

// OccupantKind distinguishes entities on a tile. OCCUPANT_MONSTER is reserved
// for future gameplay work — the current MVP only uses OCCUPANT_PLAYER.
type OccupantKind int32

const (
	OccupantKind_OCCUPANT_UNSPECIFIED OccupantKind = 0
	OccupantKind_OCCUPANT_PLAYER      OccupantKind = 1
	OccupantKind_OCCUPANT_MONSTER     OccupantKind = 2
)

// Enum value maps for OccupantKind.
var (
	OccupantKind_name = map[int32]string{
		0: "OCCUPANT_UNSPECIFIED",
		1: "OCCUPANT_PLAYER",
		2: "OCCUPANT_MONSTER",
	}
	OccupantKind_value = map[string]int32{
		"OCCUPANT_UNSPECIFIED": 0,
		"OCCUPANT_PLAYER":      1,
		"OCCUPANT_MONSTER":     2,
	}
)

func (x OccupantKind) Enum() *OccupantKind {
	p := new(OccupantKind)
	*p = x
	return p
}

func (x OccupantKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OccupantKind) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[1].Descriptor()
}

func (OccupantKind) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[1]
}

func (x OccupantKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OccupantKind.Descriptor instead.
func (OccupantKind) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{1}
}

// Structure is a single built feature on a tile — mutually exclusive.
// Binary overlay features (river, road, bridge...) go in Tile.overlays.
type Structure int32

const (
	Structure_STRUCTURE_UNSPECIFIED Structure = 0
	Structure_STRUCTURE_VILLAGE     Structure = 1
	Structure_STRUCTURE_CASTLE      Structure = 2
)

// Enum value maps for Structure.
var (
	Structure_name = map[int32]string{
		0: "STRUCTURE_UNSPECIFIED",
		1: "STRUCTURE_VILLAGE",
		2: "STRUCTURE_CASTLE",
	}
	Structure_value = map[string]int32{
		"STRUCTURE_UNSPECIFIED": 0,
		"STRUCTURE_VILLAGE":     1,
		"STRUCTURE_CASTLE":      2,
	}
)

func (x Structure) Enum() *Structure {
	p := new(Structure)
	*p = x
	return p
}

func (x Structure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Structure) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[2].Descriptor()
}

func (Structure) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[2]
}

func (x Structure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Structure.Descriptor instead.
func (Structure) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{2}
}

// LandmarkKind identifies a natural or ancient landmark on a tile. Matches
// internal/game/LandmarkKind bit-for-bit so landmarkKindPB in
// internal/server/mapper.go is a pure cast. Landmarks are a separate layer
// from Structure: a Structure is a civilization artifact (village, castle)
// while a Landmark is a geographic or pre-civilization marker (tower on a
// peak, shrine in a holy region) that exists independent of any faction.
// Zero value LANDMARK_KIND_NONE = no landmark on this tile.
type LandmarkKind int32

const (
	LandmarkKind_LANDMARK_KIND_NONE            LandmarkKind = 0
	LandmarkKind_LANDMARK_KIND_TOWER           LandmarkKind = 1
	LandmarkKind_LANDMARK_KIND_GIANT_TREE      LandmarkKind = 2
	LandmarkKind_LANDMARK_KIND_STANDING_STONES LandmarkKind = 3
	LandmarkKind_LANDMARK_KIND_OBELISK         LandmarkKind = 4
	LandmarkKind_LANDMARK_KIND_CHASM           LandmarkKind = 5
	LandmarkKind_LANDMARK_KIND_SHRINE          LandmarkKind = 6
)

// Enum value maps for LandmarkKind.
var (
	LandmarkKind_name = map[int32]string{
		0: "LANDMARK_KIND_NONE",
		1: "LANDMARK_KIND_TOWER",
		2: "LANDMARK_KIND_GIANT_TREE",
		3: "LANDMARK_KIND_STANDING_STONES",
		4: "LANDMARK_KIND_OBELISK",
		5: "LANDMARK_KIND_CHASM",
		6: "LANDMARK_KIND_SHRINE",
	}
	LandmarkKind_value = map[string]int32{
		"LANDMARK_KIND_NONE":            0,
		"LANDMARK_KIND_TOWER":           1,
		"LANDMARK_KIND_GIANT_TREE":      2,
		"LANDMARK_KIND_STANDING_STONES": 3,
		"LANDMARK_KIND_OBELISK":         4,
		"LANDMARK_KIND_CHASM":           5,
		"LANDMARK_KIND_SHRINE":          6,
	}
)

func (x LandmarkKind) Enum() *LandmarkKind {
	p := new(LandmarkKind)
	*p = x
	return p
}

func (x LandmarkKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LandmarkKind) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[3].Descriptor()
}

func (LandmarkKind) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[3]
}

func (x LandmarkKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LandmarkKind.Descriptor instead.
func (LandmarkKind) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{3}
}

// RegionCharacter is the dominant thematic identity of a Voronoi region
// cell. Matches the internal/game/RegionCharacter enum bit-for-bit so
// regionCharacterPB in internal/server/mapper.go is a pure cast.
type RegionCharacter int32

const (
	RegionCharacter_REGION_CHARACTER_NORMAL   RegionCharacter = 0
	RegionCharacter_REGION_CHARACTER_BLIGHTED RegionCharacter = 1
	RegionCharacter_REGION_CHARACTER_FEY      RegionCharacter = 2
	RegionCharacter_REGION_CHARACTER_ANCIENT  RegionCharacter = 3
	RegionCharacter_REGION_CHARACTER_SAVAGE   RegionCharacter = 4
	RegionCharacter_REGION_CHARACTER_HOLY     RegionCharacter = 5
	RegionCharacter_REGION_CHARACTER_WILD     RegionCharacter = 6
)

// Enum value maps for RegionCharacter.
var (
	RegionCharacter_name = map[int32]string{
		0: "REGION_CHARACTER_NORMAL",
		1: "REGION_CHARACTER_BLIGHTED",
		2: "REGION_CHARACTER_FEY",
		3: "REGION_CHARACTER_ANCIENT",
		4: "REGION_CHARACTER_SAVAGE",
		5: "REGION_CHARACTER_HOLY",
		6: "REGION_CHARACTER_WILD",
	}
	RegionCharacter_value = map[string]int32{
		"REGION_CHARACTER_NORMAL":   0,
		"REGION_CHARACTER_BLIGHTED": 1,
		"REGION_CHARACTER_FEY":      2,
		"REGION_CHARACTER_ANCIENT":  3,
		"REGION_CHARACTER_SAVAGE":   4,
		"REGION_CHARACTER_HOLY":     5,
		"REGION_CHARACTER_WILD":     6,
	}
)

func (x RegionCharacter) Enum() *RegionCharacter {
	p := new(RegionCharacter)
	*p = x
	return p
}

func (x RegionCharacter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegionCharacter) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[4].Descriptor()
}

func (RegionCharacter) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[4]
}

func (x RegionCharacter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegionCharacter.Descriptor instead.
func (RegionCharacter) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{4}
}

// NameFormat selects which composition template the client uses to
// render a NameParts record. Matches the naming/parts.Format enum
// bit-for-bit so the conversion is a pure cast. Do not renumber —
// legacy clients would misinterpret the format on version skew.
type NameFormat int32

const (
	NameFormat_NAME_FORMAT_UNSPECIFIED      NameFormat = 0
	NameFormat_NAME_FORMAT_BODY_ONLY        NameFormat = 1
	NameFormat_NAME_FORMAT_CHARACTER_PREFIX NameFormat = 2
	NameFormat_NAME_FORMAT_KIND_PATTERN     NameFormat = 3
)

// Enum value maps for NameFormat.
var (
	NameFormat_name = map[int32]string{
		0: "NAME_FORMAT_UNSPECIFIED",
		1: "NAME_FORMAT_BODY_ONLY",
		2: "NAME_FORMAT_CHARACTER_PREFIX",
		3: "NAME_FORMAT_KIND_PATTERN",
	}
	NameFormat_value = map[string]int32{
		"NAME_FORMAT_UNSPECIFIED":      0,
		"NAME_FORMAT_BODY_ONLY":        1,
		"NAME_FORMAT_CHARACTER_PREFIX": 2,
		"NAME_FORMAT_KIND_PATTERN":     3,
	}
)

func (x NameFormat) Enum() *NameFormat {
	p := new(NameFormat)
	*p = x
	return p
}

func (x NameFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NameFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_gongeons_proto_enumTypes[5].Descriptor()
}

func (NameFormat) Type() protoreflect.EnumType {
	return &file_gongeons_proto_enumTypes[5]
}

func (x NameFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NameFormat.Descriptor instead.
func (NameFormat) EnumDescriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{5}
}

// Position is an absolute square-grid tile coordinate. Origin is arbitrary
// (world 0, 0); the coordinate system is unbounded in both axes.
type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_gongeons_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

// NameParts is the language-agnostic structured name carried on every
// named entity (Region, Landmark, future Settlement). The client
// composes the final display string locally: it looks up the template
// for the chosen Format in its locale catalog under the domain-specific
// namespace and fills in Body by seeding its embedded Markov corpus
// with body_seed. No body text travels the wire — the server stays
// language-agnostic while the client renders en/ru/etc.
type NameParts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     string                 `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	SubKind       string                 `protobuf:"bytes,2,opt,name=sub_kind,json=subKind,proto3" json:"sub_kind,omitempty"`
	Format        NameFormat             `protobuf:"varint,3,opt,name=format,proto3,enum=gongeons.v1.NameFormat" json:"format,omitempty"`
	PrefixIndex   uint32                 `protobuf:"varint,4,opt,name=prefix_index,json=prefixIndex,proto3" json:"prefix_index,omitempty"`
	PatternIndex  uint32                 `protobuf:"varint,5,opt,name=pattern_index,json=patternIndex,proto3" json:"pattern_index,omitempty"`
	BodySeed      int64                  `protobuf:"varint,6,opt,name=body_seed,json=bodySeed,proto3" json:"body_seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameParts) Reset() {
	*x = NameParts{}
	mi := &file_gongeons_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameParts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameParts) ProtoMessage() {}

func (x *NameParts) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameParts.ProtoReflect.Descriptor instead.
func (*NameParts) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{1}
}

func (x *NameParts) GetCharacter() string {
	if x != nil {
		return x.Character
	}
	return ""
}

func (x *NameParts) GetSubKind() string {
	if x != nil {
		return x.SubKind
	}
	return ""
}

func (x *NameParts) GetFormat() NameFormat {
	if x != nil {
		return x.Format
	}
	return NameFormat_NAME_FORMAT_UNSPECIFIED
}

func (x *NameParts) GetPrefixIndex() uint32 {
	if x != nil {
		return x.PrefixIndex
	}
	return 0
}

func (x *NameParts) GetPatternIndex() uint32 {
	if x != nil {
		return x.PatternIndex
	}
	return 0
}

func (x *NameParts) GetBodySeed() int64 {
	if x != nil {
		return x.BodySeed
	}
	return 0
}

// Landmark is a structured landmark record carried on Tile. Kind picks
// the glyph and affinity rules; Name is composed into a display string
// client-side from the NameParts plus a locale catalog.
type Landmark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          LandmarkKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=gongeons.v1.LandmarkKind" json:"kind,omitempty"`
	Name          *NameParts             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Landmark) Reset() {
	*x = Landmark{}
	mi := &file_gongeons_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Landmark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Landmark) ProtoMessage() {}

func (x *Landmark) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Landmark.ProtoReflect.Descriptor instead.
func (*Landmark) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{2}
}

func (x *Landmark) GetKind() LandmarkKind {
	if x != nil {
		return x.Kind
	}
	return LandmarkKind_LANDMARK_KIND_NONE
}

func (x *Landmark) GetName() *NameParts {
	if x != nil {
		return x.Name
	}
	return nil
}

// RegionInfluence mirrors the game-side struct. Sent to clients so they
// can reason about sub-dominant influences (e.g. a Fey region with
// significant Ancient undertones) and blend per-tile tints without
// round-tripping the server.
type RegionInfluence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blight        float32                `protobuf:"fixed32,1,opt,name=blight,proto3" json:"blight,omitempty"`
	Fae           float32                `protobuf:"fixed32,2,opt,name=fae,proto3" json:"fae,omitempty"`
	Ancient       float32                `protobuf:"fixed32,3,opt,name=ancient,proto3" json:"ancient,omitempty"`
	Savage        float32                `protobuf:"fixed32,4,opt,name=savage,proto3" json:"savage,omitempty"`
	Holy          float32                `protobuf:"fixed32,5,opt,name=holy,proto3" json:"holy,omitempty"`
	Wild          float32                `protobuf:"fixed32,6,opt,name=wild,proto3" json:"wild,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionInfluence) Reset() {
	*x = RegionInfluence{}
	mi := &file_gongeons_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionInfluence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionInfluence) ProtoMessage() {}

func (x *RegionInfluence) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionInfluence.ProtoReflect.Descriptor instead.
func (*RegionInfluence) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{3}
}

func (x *RegionInfluence) GetBlight() float32 {
	if x != nil {
		return x.Blight
	}
	return 0
}

func (x *RegionInfluence) GetFae() float32 {
	if x != nil {
		return x.Fae
	}
	return 0
}

func (x *RegionInfluence) GetAncient() float32 {
	if x != nil {
		return x.Ancient
	}
	return 0
}

func (x *RegionInfluence) GetSavage() float32 {
	if x != nil {
		return x.Savage
	}
	return 0
}

func (x *RegionInfluence) GetHoly() float32 {
	if x != nil {
		return x.Holy
	}
	return 0
}

func (x *RegionInfluence) GetWild() float32 {
	if x != nil {
		return x.Wild
	}
	return 0
}

// Region carries anchor-level character, name, and influence for the
// Voronoi cell containing the receiving player. Anchor position is NOT
// on the wire — clients derive it via AnchorOf(world_seed, {super_chunk_x,
// super_chunk_y}). The world seed is delivered once in JoinAccepted.
//
// Tag 3 previously held a flat `string name` rendered server-side. It
// is reserved so future proto evolutions cannot accidentally reuse it
// with a different type; the structured name lives at tag 6.
type Region struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuperChunkX   int32                  `protobuf:"varint,1,opt,name=super_chunk_x,json=superChunkX,proto3" json:"super_chunk_x,omitempty"`
	SuperChunkY   int32                  `protobuf:"varint,2,opt,name=super_chunk_y,json=superChunkY,proto3" json:"super_chunk_y,omitempty"`
	Character     RegionCharacter        `protobuf:"varint,4,opt,name=character,proto3,enum=gongeons.v1.RegionCharacter" json:"character,omitempty"`
	Influence     *RegionInfluence       `protobuf:"bytes,5,opt,name=influence,proto3" json:"influence,omitempty"`
	Name          *NameParts             `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Region) Reset() {
	*x = Region{}
	mi := &file_gongeons_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Region) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Region) ProtoMessage() {}

func (x *Region) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Region.ProtoReflect.Descriptor instead.
func (*Region) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{4}
}

func (x *Region) GetSuperChunkX() int32 {
	if x != nil {
		return x.SuperChunkX
	}
	return 0
}

func (x *Region) GetSuperChunkY() int32 {
	if x != nil {
		return x.SuperChunkY
	}
	return 0
}

func (x *Region) GetCharacter() RegionCharacter {
	if x != nil {
		return x.Character
	}
	return RegionCharacter_REGION_CHARACTER_NORMAL
}

func (x *Region) GetInfluence() *RegionInfluence {
	if x != nil {
		return x.Influence
	}
	return nil
}

func (x *Region) GetName() *NameParts {
	if x != nil {
		return x.Name
	}
	return nil
}

// LocalizedMessage is the server-to-client envelope for localized errors
// and events. The server emits a stable message_id (catalog key) plus
// template args; the client renders the final string through its i18n
// bundle keyed on the player's language. Server logs still carry the
// English Status message for developer diagnostics.
type LocalizedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Args          map[string]string      `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocalizedMessage) Reset() {
	*x = LocalizedMessage{}
	mi := &file_gongeons_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalizedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalizedMessage) ProtoMessage() {}

func (x *LocalizedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalizedMessage.ProtoReflect.Descriptor instead.
func (*LocalizedMessage) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{5}
}

func (x *LocalizedMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *LocalizedMessage) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

// Tile is an atomic map cell. Used in Snapshot only — Events carry deltas,
// not full tile replacements. overlays is a bitmask of TileOverlay flag
// values shared with the domain (river, road, bridge, path...).
//
// Historical: fields 4 and 5 previously held `bool river` and
// `WorldObject object`. They were re-typed to uint32 + Structure during
// the overlay-bitmask refactor; the slot numbers were deliberately
// reused. Do not reintroduce the old field names on different slots —
// future overlays should get fresh numbers (6, 7, ...).
type Tile struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Terrain  Terrain                `protobuf:"varint,1,opt,name=terrain,proto3,enum=gongeons.v1.Terrain" json:"terrain,omitempty"`
	Occupant OccupantKind           `protobuf:"varint,2,opt,name=occupant,proto3,enum=gongeons.v1.OccupantKind" json:"occupant,omitempty"`
	EntityId string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // occupant ID, empty if no occupant
	// overlays is a bitmask of yes/no tile features (river, road, bridge,
	// path...). Bit values are defined in Go as TileOverlay constants in
	// internal/game/overlay.go:
	//
	//	bit 0 (value 1)  = OverlayRiver
	//	bit 1 (value 2)  = OverlayRoad
	//	bit 2 (value 4)  = OverlayBridge
	//	bit 3 (value 8)  = OverlayPath
	//
	// Bits 4-31 are reserved for future overlays. Keep overlay.go and this
	// comment in lockstep when adding a new flag.
	Overlays  uint32    `protobuf:"varint,4,opt,name=overlays,proto3" json:"overlays,omitempty"`
	Structure Structure `protobuf:"varint,5,opt,name=structure,proto3,enum=gongeons.v1.Structure" json:"structure,omitempty"` // village / castle overlay
	// landmark is the natural or ancient landmark on this tile, or nil
	// when nothing is placed. Landmark is a separate layer from
	// structure — see the LandmarkKind enum comment above.
	Landmark      *Landmark `protobuf:"bytes,7,opt,name=landmark,proto3" json:"landmark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_gongeons_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{6}
}

func (x *Tile) GetTerrain() Terrain {
	if x != nil {
		return x.Terrain
	}
	return Terrain_TERRAIN_UNSPECIFIED
}

func (x *Tile) GetOccupant() OccupantKind {
	if x != nil {
		return x.Occupant
	}
	return OccupantKind_OCCUPANT_UNSPECIFIED
}

func (x *Tile) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Tile) GetOverlays() uint32 {
	if x != nil {
		return x.Overlays
	}
	return 0
}

func (x *Tile) GetStructure() Structure {
	if x != nil {
		return x.Structure
	}
	return Structure_STRUCTURE_UNSPECIFIED
}

func (x *Tile) GetLandmark() *Landmark {
	if x != nil {
		return x.Landmark
	}
	return nil
}

// Entity is a positioned actor in the world. Combat stats / monsters are
// added in a later phase on top of this shape.
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          OccupantKind           `protobuf:"varint,3,opt,name=kind,proto3,enum=gongeons.v1.OccupantKind" json:"kind,omitempty"`
	Position      *Position              `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_gongeons_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{7}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entity) GetKind() OccupantKind {
	if x != nil {
		return x.Kind
	}
	return OccupantKind_OCCUPANT_UNSPECIFIED
}

func (x *Entity) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientMessage_Join
	//	*ClientMessage_Move
	//	*ClientMessage_Viewport
	Payload       isClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_gongeons_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{8}
}

func (x *ClientMessage) GetPayload() isClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientMessage) GetJoin() *JoinRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *ClientMessage) GetMove() *MoveCmd {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

func (x *ClientMessage) GetViewport() *ViewportCmd {
	if x != nil {
		if x, ok := x.Payload.(*ClientMessage_Viewport); ok {
			return x.Viewport
		}
	}
	return nil
}

type isClientMessage_Payload interface {
	isClientMessage_Payload()
}

type ClientMessage_Join struct {
	Join *JoinRequest `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type ClientMessage_Move struct {
	Move *MoveCmd `protobuf:"bytes,2,opt,name=move,proto3,oneof"`
}

type ClientMessage_Viewport struct {
	Viewport *ViewportCmd `protobuf:"bytes,3,opt,name=viewport,proto3,oneof"`
}

func (*ClientMessage_Join) isClientMessage_Payload() {}

func (*ClientMessage_Move) isClientMessage_Payload() {}

func (*ClientMessage_Viewport) isClientMessage_Payload() {}

// CoreStats mirrors game.CoreStats for the join handshake. The client
// sends the six D&D 5e ability scores the player assembled during
// character creation (CS4); the server validates the Point Buy 27 budget
// before accepting and rejects a bad distribution with error.invalid_stats.
// When the whole message is omitted the server substitutes a neutral
// baseline (all 10s) so legacy clients keep working.
type CoreStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strength      int32                  `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"`
	Dexterity     int32                  `protobuf:"varint,2,opt,name=dexterity,proto3" json:"dexterity,omitempty"`
	Constitution  int32                  `protobuf:"varint,3,opt,name=constitution,proto3" json:"constitution,omitempty"`
	Intelligence  int32                  `protobuf:"varint,4,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Wisdom        int32                  `protobuf:"varint,5,opt,name=wisdom,proto3" json:"wisdom,omitempty"`
	Charisma      int32                  `protobuf:"varint,6,opt,name=charisma,proto3" json:"charisma,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreStats) Reset() {
	*x = CoreStats{}
	mi := &file_gongeons_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreStats) ProtoMessage() {}

func (x *CoreStats) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreStats.ProtoReflect.Descriptor instead.
func (*CoreStats) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{9}
}

func (x *CoreStats) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *CoreStats) GetDexterity() int32 {
	if x != nil {
		return x.Dexterity
	}
	return 0
}

func (x *CoreStats) GetConstitution() int32 {
	if x != nil {
		return x.Constitution
	}
	return 0
}

func (x *CoreStats) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *CoreStats) GetWisdom() int32 {
	if x != nil {
		return x.Wisdom
	}
	return 0
}

func (x *CoreStats) GetCharisma() int32 {
	if x != nil {
		return x.Charisma
	}
	return 0
}

// JoinRequest is the first message a client sends. The server assigns a
// PlayerID in JoinAccepted and begins broadcasting events to this stream.
// viewport_width and viewport_height are the desired Snapshot dimensions
// for this client; zero means "use server defaults". language is the
// client's preferred locale as a BCP 47 tag (e.g. "en", "ru"); empty
// means the server picks "en" as default — locale catalog wiring is handled
// server-side. stats carries the character's D&D 5e ability distribution;
// omit it (or send zeroes) to get the server's neutral fallback.
type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ViewportWidth  int32                  `protobuf:"varint,2,opt,name=viewport_width,json=viewportWidth,proto3" json:"viewport_width,omitempty"`
	ViewportHeight int32                  `protobuf:"varint,3,opt,name=viewport_height,json=viewportHeight,proto3" json:"viewport_height,omitempty"`
	Language       string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Stats          *CoreStats             `protobuf:"bytes,5,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_gongeons_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JoinRequest) GetViewportWidth() int32 {
	if x != nil {
		return x.ViewportWidth
	}
	return 0
}

func (x *JoinRequest) GetViewportHeight() int32 {
	if x != nil {
		return x.ViewportHeight
	}
	return 0
}

func (x *JoinRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *JoinRequest) GetStats() *CoreStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// ViewportCmd updates the Snapshot dimensions the server should use for
// this client — the terminal resized, we want a bigger / smaller view.
// The server replies with a fresh Snapshot at the new size.
type ViewportCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewportCmd) Reset() {
	*x = ViewportCmd{}
	mi := &file_gongeons_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewportCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewportCmd) ProtoMessage() {}

func (x *ViewportCmd) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewportCmd.ProtoReflect.Descriptor instead.
func (*ViewportCmd) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{11}
}

func (x *ViewportCmd) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ViewportCmd) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// MoveCmd asks to move one step. dx/dy are in {-1, 0, 1}; exactly one is
// non-zero (four-directional movement via WASD).
type MoveCmd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dx            int32                  `protobuf:"varint,1,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy            int32                  `protobuf:"varint,2,opt,name=dy,proto3" json:"dy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCmd) Reset() {
	*x = MoveCmd{}
	mi := &file_gongeons_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCmd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCmd) ProtoMessage() {}

func (x *MoveCmd) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCmd.ProtoReflect.Descriptor instead.
func (*MoveCmd) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{12}
}

func (x *MoveCmd) GetDx() int32 {
	if x != nil {
		return x.Dx
	}
	return 0
}

func (x *MoveCmd) GetDy() int32 {
	if x != nil {
		return x.Dy
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerMessage_Accepted
	//	*ServerMessage_Snapshot
	//	*ServerMessage_Event
	//	*ServerMessage_Error
	Payload       isServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_gongeons_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{13}
}

func (x *ServerMessage) GetPayload() isServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerMessage) GetAccepted() *JoinAccepted {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *ServerMessage) GetSnapshot() *Snapshot {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *ServerMessage) GetEvent() *Event {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Event); ok {
			return x.Event
		}
	}
	return nil
}

func (x *ServerMessage) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Payload.(*ServerMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isServerMessage_Payload interface {
	isServerMessage_Payload()
}

type ServerMessage_Accepted struct {
	Accepted *JoinAccepted `protobuf:"bytes,1,opt,name=accepted,proto3,oneof"`
}

type ServerMessage_Snapshot struct {
	Snapshot *Snapshot `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type ServerMessage_Event struct {
	Event *Event `protobuf:"bytes,3,opt,name=event,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *ErrorResponse `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*ServerMessage_Accepted) isServerMessage_Payload() {}

func (*ServerMessage_Snapshot) isServerMessage_Payload() {}

func (*ServerMessage_Event) isServerMessage_Payload() {}

func (*ServerMessage_Error) isServerMessage_Payload() {}

// JoinAccepted is the server's reply to JoinRequest. It carries the generated
// PlayerID and the player's spawn position — the client stores the ID and
// uses it to recognise its own events. world_seed is forwarded so the
// client can construct a local region source for per-tile influence
// sampling (cosmetic only, not authoritative state).
type JoinAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Spawn         *Position              `protobuf:"bytes,2,opt,name=spawn,proto3" json:"spawn,omitempty"`
	WorldSeed     int64                  `protobuf:"varint,3,opt,name=world_seed,json=worldSeed,proto3" json:"world_seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinAccepted) Reset() {
	*x = JoinAccepted{}
	mi := &file_gongeons_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinAccepted) ProtoMessage() {}

func (x *JoinAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinAccepted.ProtoReflect.Descriptor instead.
func (*JoinAccepted) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{14}
}

func (x *JoinAccepted) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *JoinAccepted) GetSpawn() *Position {
	if x != nil {
		return x.Spawn
	}
	return nil
}

func (x *JoinAccepted) GetWorldSeed() int64 {
	if x != nil {
		return x.WorldSeed
	}
	return 0
}

// Snapshot is a viewport of the world. Width/height are tile counts; origin
// is the world-space position of the top-left tile. Tiles are row-major of
// length width*height.
type Snapshot struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Width    int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height   int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Origin   *Position              `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Tiles    []*Tile                `protobuf:"bytes,4,rep,name=tiles,proto3" json:"tiles,omitempty"`
	Entities []*Entity              `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	// region at this player's position (per-player, not shared). Clients
	// use it for status-bar rendering, tint, and boundary-crossing events.
	Region *Region `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	// self_energy is the receiving player's current Energy counter for the
	// tick system. int32 because proto has no native int; domain values
	// are always non-negative. Private to the snapshot subject — never sent
	// in broadcasts to other players.
	SelfEnergy int32 `protobuf:"varint,7,opt,name=self_energy,json=selfEnergy,proto3" json:"self_energy,omitempty"`
	// self_energy_cost is the Energy required to perform a standard action
	// (BaseActionCost = 12). Sent as a constant so the client can render
	// the denominator of the energy bar (e.g. "8/12") without hard-coding
	// the server constant.
	SelfEnergyCost int32 `protobuf:"varint,8,opt,name=self_energy_cost,json=selfEnergyCost,proto3" json:"self_energy_cost,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_gongeons_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{15}
}

func (x *Snapshot) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Snapshot) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Snapshot) GetOrigin() *Position {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *Snapshot) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *Snapshot) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *Snapshot) GetRegion() *Region {
	if x != nil {
		return x.Region
	}
	return nil
}

func (x *Snapshot) GetSelfEnergy() int32 {
	if x != nil {
		return x.SelfEnergy
	}
	return 0
}

func (x *Snapshot) GetSelfEnergyCost() int32 {
	if x != nil {
		return x.SelfEnergyCost
	}
	return 0
}

// Event is a domain event the server broadcasts to every connected client.
// The client applies it to its local Model to stay in sync.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_PlayerJoined
	//	*Event_PlayerLeft
	//	*Event_EntityMoved
	//	*Event_IntentFailed
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_gongeons_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{16}
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetPlayerJoined() *PlayerJoined {
	if x != nil {
		if x, ok := x.Payload.(*Event_PlayerJoined); ok {
			return x.PlayerJoined
		}
	}
	return nil
}

func (x *Event) GetPlayerLeft() *PlayerLeft {
	if x != nil {
		if x, ok := x.Payload.(*Event_PlayerLeft); ok {
			return x.PlayerLeft
		}
	}
	return nil
}

func (x *Event) GetEntityMoved() *EntityMoved {
	if x != nil {
		if x, ok := x.Payload.(*Event_EntityMoved); ok {
			return x.EntityMoved
		}
	}
	return nil
}

func (x *Event) GetIntentFailed() *IntentFailed {
	if x != nil {
		if x, ok := x.Payload.(*Event_IntentFailed); ok {
			return x.IntentFailed
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_PlayerJoined struct {
	PlayerJoined *PlayerJoined `protobuf:"bytes,1,opt,name=player_joined,json=playerJoined,proto3,oneof"`
}

type Event_PlayerLeft struct {
	PlayerLeft *PlayerLeft `protobuf:"bytes,2,opt,name=player_left,json=playerLeft,proto3,oneof"`
}

type Event_EntityMoved struct {
	EntityMoved *EntityMoved `protobuf:"bytes,3,opt,name=entity_moved,json=entityMoved,proto3,oneof"`
}

type Event_IntentFailed struct {
	IntentFailed *IntentFailed `protobuf:"bytes,4,opt,name=intent_failed,json=intentFailed,proto3,oneof"`
}

func (*Event_PlayerJoined) isEvent_Payload() {}

func (*Event_PlayerLeft) isEvent_Payload() {}

func (*Event_EntityMoved) isEvent_Payload() {}

func (*Event_IntentFailed) isEvent_Payload() {}

type PlayerJoined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        *Entity                `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerJoined) Reset() {
	*x = PlayerJoined{}
	mi := &file_gongeons_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerJoined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerJoined) ProtoMessage() {}

func (x *PlayerJoined) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerJoined.ProtoReflect.Descriptor instead.
func (*PlayerJoined) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{17}
}

func (x *PlayerJoined) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type PlayerLeft struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerLeft) Reset() {
	*x = PlayerLeft{}
	mi := &file_gongeons_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerLeft) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerLeft) ProtoMessage() {}

func (x *PlayerLeft) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerLeft.ProtoReflect.Descriptor instead.
func (*PlayerLeft) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{18}
}

func (x *PlayerLeft) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

type EntityMoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	From          *Position              `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            *Position              `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityMoved) Reset() {
	*x = EntityMoved{}
	mi := &file_gongeons_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityMoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityMoved) ProtoMessage() {}

func (x *EntityMoved) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityMoved.ProtoReflect.Descriptor instead.
func (*EntityMoved) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{19}
}

func (x *EntityMoved) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityMoved) GetFrom() *Position {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EntityMoved) GetTo() *Position {
	if x != nil {
		return x.To
	}
	return nil
}

// IntentFailed reports that an entity's pending intent (MoveIntent, future
// AttackIntent, ...) could not resolve at Tick time — destination blocked,
// target dead, etc. Energy is NOT deducted on the server (refund
// semantics): the intent slot is cleared so the entity becomes idle and
// its next input is free. reason is a stable locale catalog key (e.g.
// "error.intent.move_blocked"); the client renders the player-facing text
// via its i18n bundle, keeping the wire language-agnostic.
type IntentFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentFailed) Reset() {
	*x = IntentFailed{}
	mi := &file_gongeons_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentFailed) ProtoMessage() {}

func (x *IntentFailed) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentFailed.ProtoReflect.Descriptor instead.
func (*IntentFailed) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{20}
}

func (x *IntentFailed) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *IntentFailed) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_gongeons_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gongeons_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_gongeons_proto_rawDescGZIP(), []int{21}
}

func (x *ErrorResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_gongeons_proto protoreflect.FileDescriptor

const file_gongeons_proto_rawDesc = "" +
	"\n" +
	"\x0egongeons.proto\x12\vgongeons.v1\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xda\x01\n" +
	"\tNameParts\x12\x1c\n" +
	"\tcharacter\x18\x01 \x01(\tR\tcharacter\x12\x19\n" +
	"\bsub_kind\x18\x02 \x01(\tR\asubKind\x12/\n" +
	"\x06format\x18\x03 \x01(\x0e2\x17.gongeons.v1.NameFormatR\x06format\x12!\n" +
	"\fprefix_index\x18\x04 \x01(\rR\vprefixIndex\x12#\n" +
	"\rpattern_index\x18\x05 \x01(\rR\fpatternIndex\x12\x1b\n" +
	"\tbody_seed\x18\x06 \x01(\x03R\bbodySeed\"e\n" +
	"\bLandmark\x12-\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x19.gongeons.v1.LandmarkKindR\x04kind\x12*\n" +
	"\x04name\x18\x02 \x01(\v2\x16.gongeons.v1.NamePartsR\x04name\"\x95\x01\n" +
	"\x0fRegionInfluence\x12\x16\n" +
	"\x06blight\x18\x01 \x01(\x02R\x06blight\x12\x10\n" +
	"\x03fae\x18\x02 \x01(\x02R\x03fae\x12\x18\n" +
	"\aancient\x18\x03 \x01(\x02R\aancient\x12\x16\n" +
	"\x06savage\x18\x04 \x01(\x02R\x06savage\x12\x12\n" +
	"\x04holy\x18\x05 \x01(\x02R\x04holy\x12\x12\n" +
	"\x04wild\x18\x06 \x01(\x02R\x04wild\"\xfa\x01\n" +
	"\x06Region\x12\"\n" +
	"\rsuper_chunk_x\x18\x01 \x01(\x05R\vsuperChunkX\x12\"\n" +
	"\rsuper_chunk_y\x18\x02 \x01(\x05R\vsuperChunkY\x12:\n" +
	"\tcharacter\x18\x04 \x01(\x0e2\x1c.gongeons.v1.RegionCharacterR\tcharacter\x12:\n" +
	"\tinfluence\x18\x05 \x01(\v2\x1c.gongeons.v1.RegionInfluenceR\tinfluence\x12*\n" +
	"\x04name\x18\x06 \x01(\v2\x16.gongeons.v1.NamePartsR\x04nameJ\x04\b\x03\x10\x04\"\xa7\x01\n" +
	"\x10LocalizedMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12;\n" +
	"\x04args\x18\x02 \x03(\v2'.gongeons.v1.LocalizedMessage.ArgsEntryR\x04args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x02\n" +
	"\x04Tile\x12.\n" +
	"\aterrain\x18\x01 \x01(\x0e2\x14.gongeons.v1.TerrainR\aterrain\x125\n" +
	"\boccupant\x18\x02 \x01(\x0e2\x19.gongeons.v1.OccupantKindR\boccupant\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1a\n" +
	"\boverlays\x18\x04 \x01(\rR\boverlays\x124\n" +
	"\tstructure\x18\x05 \x01(\x0e2\x16.gongeons.v1.StructureR\tstructure\x121\n" +
	"\blandmark\x18\a \x01(\v2\x15.gongeons.v1.LandmarkR\blandmarkJ\x04\b\x06\x10\a\"\x8e\x01\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x19.gongeons.v1.OccupantKindR\x04kind\x121\n" +
	"\bposition\x18\x04 \x01(\v2\x15.gongeons.v1.PositionR\bposition\"\xae\x01\n" +
	"\rClientMessage\x12.\n" +
	"\x04join\x18\x01 \x01(\v2\x18.gongeons.v1.JoinRequestH\x00R\x04join\x12*\n" +
	"\x04move\x18\x02 \x01(\v2\x14.gongeons.v1.MoveCmdH\x00R\x04move\x126\n" +
	"\bviewport\x18\x03 \x01(\v2\x18.gongeons.v1.ViewportCmdH\x00R\bviewportB\t\n" +
	"\apayload\"\xc1\x01\n" +
	"\tCoreStats\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x05R\bstrength\x12\x1c\n" +
	"\tdexterity\x18\x02 \x01(\x05R\tdexterity\x12\"\n" +
	"\fconstitution\x18\x03 \x01(\x05R\fconstitution\x12\"\n" +
	"\fintelligence\x18\x04 \x01(\x05R\fintelligence\x12\x16\n" +
	"\x06wisdom\x18\x05 \x01(\x05R\x06wisdom\x12\x1a\n" +
	"\bcharisma\x18\x06 \x01(\x05R\bcharisma\"\xbb\x01\n" +
	"\vJoinRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\x0eviewport_width\x18\x02 \x01(\x05R\rviewportWidth\x12'\n" +
	"\x0fviewport_height\x18\x03 \x01(\x05R\x0eviewportHeight\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12,\n" +
	"\x05stats\x18\x05 \x01(\v2\x16.gongeons.v1.CoreStatsR\x05stats\";\n" +
	"\vViewportCmd\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\")\n" +
	"\aMoveCmd\x12\x0e\n" +
	"\x02dx\x18\x01 \x01(\x05R\x02dx\x12\x0e\n" +
	"\x02dy\x18\x02 \x01(\x05R\x02dy\"\xe8\x01\n" +
	"\rServerMessage\x127\n" +
	"\baccepted\x18\x01 \x01(\v2\x19.gongeons.v1.JoinAcceptedH\x00R\baccepted\x123\n" +
	"\bsnapshot\x18\x02 \x01(\v2\x15.gongeons.v1.SnapshotH\x00R\bsnapshot\x12*\n" +
	"\x05event\x18\x03 \x01(\v2\x12.gongeons.v1.EventH\x00R\x05event\x122\n" +
	"\x05error\x18\x04 \x01(\v2\x1a.gongeons.v1.ErrorResponseH\x00R\x05errorB\t\n" +
	"\apayload\"w\n" +
	"\fJoinAccepted\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12+\n" +
	"\x05spawn\x18\x02 \x01(\v2\x15.gongeons.v1.PositionR\x05spawn\x12\x1d\n" +
	"\n" +
	"world_seed\x18\x03 \x01(\x03R\tworldSeed\"\xb9\x02\n" +
	"\bSnapshot\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12-\n" +
	"\x06origin\x18\x03 \x01(\v2\x15.gongeons.v1.PositionR\x06origin\x12'\n" +
	"\x05tiles\x18\x04 \x03(\v2\x11.gongeons.v1.TileR\x05tiles\x12/\n" +
	"\bentities\x18\x05 \x03(\v2\x13.gongeons.v1.EntityR\bentities\x12+\n" +
	"\x06region\x18\x06 \x01(\v2\x13.gongeons.v1.RegionR\x06region\x12\x1f\n" +
	"\vself_energy\x18\a \x01(\x05R\n" +
	"selfEnergy\x12(\n" +
	"\x10self_energy_cost\x18\b \x01(\x05R\x0eselfEnergyCost\"\x91\x02\n" +
	"\x05Event\x12@\n" +
	"\rplayer_joined\x18\x01 \x01(\v2\x19.gongeons.v1.PlayerJoinedH\x00R\fplayerJoined\x12:\n" +
	"\vplayer_left\x18\x02 \x01(\v2\x17.gongeons.v1.PlayerLeftH\x00R\n" +
	"playerLeft\x12=\n" +
	"\fentity_moved\x18\x03 \x01(\v2\x18.gongeons.v1.EntityMovedH\x00R\ventityMoved\x12@\n" +
	"\rintent_failed\x18\x04 \x01(\v2\x19.gongeons.v1.IntentFailedH\x00R\fintentFailedB\t\n" +
	"\apayload\";\n" +
	"\fPlayerJoined\x12+\n" +
	"\x06entity\x18\x01 \x01(\v2\x13.gongeons.v1.EntityR\x06entity\")\n" +
	"\n" +
	"PlayerLeft\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\"|\n" +
	"\vEntityMoved\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12)\n" +
	"\x04from\x18\x02 \x01(\v2\x15.gongeons.v1.PositionR\x04from\x12%\n" +
	"\x02to\x18\x03 \x01(\v2\x15.gongeons.v1.PositionR\x02to\"C\n" +
	"\fIntentFailed\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"=\n" +
	"\rErrorResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code*\xea\x02\n" +
	"\aTerrain\x12\x17\n" +
	"\x13TERRAIN_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTERRAIN_PLAINS\x10\x01\x12\x15\n" +
	"\x11TERRAIN_GRASSLAND\x10\x02\x12\x12\n" +
	"\x0eTERRAIN_MEADOW\x10\x03\x12\x11\n" +
	"\rTERRAIN_BEACH\x10\x04\x12\x12\n" +
	"\x0eTERRAIN_DESERT\x10\x05\x12\x13\n" +
	"\x0fTERRAIN_SAVANNA\x10\x06\x12\x12\n" +
	"\x0eTERRAIN_FOREST\x10\a\x12\x12\n" +
	"\x0eTERRAIN_JUNGLE\x10\b\x12\x11\n" +
	"\rTERRAIN_TAIGA\x10\t\x12\x12\n" +
	"\x0eTERRAIN_TUNDRA\x10\n" +
	"\x12\x10\n" +
	"\fTERRAIN_SNOW\x10\v\x12\x11\n" +
	"\rTERRAIN_HILLS\x10\f\x12\x14\n" +
	"\x10TERRAIN_MOUNTAIN\x10\r\x12\x16\n" +
	"\x12TERRAIN_SNOWY_PEAK\x10\x0e\x12\x11\n" +
	"\rTERRAIN_OCEAN\x10\x0f\x12\x16\n" +
	"\x12TERRAIN_DEEP_OCEAN\x10\x10*S\n" +
	"\fOccupantKind\x12\x18\n" +
	"\x14OCCUPANT_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOCCUPANT_PLAYER\x10\x01\x12\x14\n" +
	"\x10OCCUPANT_MONSTER\x10\x02*S\n" +
	"\tStructure\x12\x19\n" +
	"\x15STRUCTURE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11STRUCTURE_VILLAGE\x10\x01\x12\x14\n" +
	"\x10STRUCTURE_CASTLE\x10\x02*\xce\x01\n" +
	"\fLandmarkKind\x12\x16\n" +
	"\x12LANDMARK_KIND_NONE\x10\x00\x12\x17\n" +
	"\x13LANDMARK_KIND_TOWER\x10\x01\x12\x1c\n" +
	"\x18LANDMARK_KIND_GIANT_TREE\x10\x02\x12!\n" +
	"\x1dLANDMARK_KIND_STANDING_STONES\x10\x03\x12\x19\n" +
	"\x15LANDMARK_KIND_OBELISK\x10\x04\x12\x17\n" +
	"\x13LANDMARK_KIND_CHASM\x10\x05\x12\x18\n" +
	"\x14LANDMARK_KIND_SHRINE\x10\x06*\xd8\x01\n" +
	"\x0fRegionCharacter\x12\x1b\n" +
	"\x17REGION_CHARACTER_NORMAL\x10\x00\x12\x1d\n" +
	"\x19REGION_CHARACTER_BLIGHTED\x10\x01\x12\x18\n" +
	"\x14REGION_CHARACTER_FEY\x10\x02\x12\x1c\n" +
	"\x18REGION_CHARACTER_ANCIENT\x10\x03\x12\x1b\n" +
	"\x17REGION_CHARACTER_SAVAGE\x10\x04\x12\x19\n" +
	"\x15REGION_CHARACTER_HOLY\x10\x05\x12\x19\n" +
	"\x15REGION_CHARACTER_WILD\x10\x06*\x84\x01\n" +
	"\n" +
	"NameFormat\x12\x1b\n" +
	"\x17NAME_FORMAT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15NAME_FORMAT_BODY_ONLY\x10\x01\x12 \n" +
	"\x1cNAME_FORMAT_CHARACTER_PREFIX\x10\x02\x12\x1c\n" +
	"\x18NAME_FORMAT_KIND_PATTERN\x10\x032Q\n" +
	"\vGameService\x12B\n" +
	"\x04Play\x12\x1a.gongeons.v1.ClientMessage\x1a\x1a.gongeons.v1.ServerMessage(\x010\x01B8Z6github.com/Rioverde/gongeons/internal/proto;gongeonspbb\x06proto3"

var (
	file_gongeons_proto_rawDescOnce sync.Once
	file_gongeons_proto_rawDescData []byte
)

func file_gongeons_proto_rawDescGZIP() []byte {
	file_gongeons_proto_rawDescOnce.Do(func() {
		file_gongeons_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gongeons_proto_rawDesc), len(file_gongeons_proto_rawDesc)))
	})
	return file_gongeons_proto_rawDescData
}

var file_gongeons_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_gongeons_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_gongeons_proto_goTypes = []any{
	(Terrain)(0),             // 0: gongeons.v1.Terrain
	(OccupantKind)(0),        // 1: gongeons.v1.OccupantKind
	(Structure)(0),           // 2: gongeons.v1.Structure
	(LandmarkKind)(0),        // 3: gongeons.v1.LandmarkKind
	(RegionCharacter)(0),     // 4: gongeons.v1.RegionCharacter
	(NameFormat)(0),          // 5: gongeons.v1.NameFormat
	(*Position)(nil),         // 6: gongeons.v1.Position
	(*NameParts)(nil),        // 7: gongeons.v1.NameParts
	(*Landmark)(nil),         // 8: gongeons.v1.Landmark
	(*RegionInfluence)(nil),  // 9: gongeons.v1.RegionInfluence
	(*Region)(nil),           // 10: gongeons.v1.Region
	(*LocalizedMessage)(nil), // 11: gongeons.v1.LocalizedMessage
	(*Tile)(nil),             // 12: gongeons.v1.Tile
	(*Entity)(nil),           // 13: gongeons.v1.Entity
	(*ClientMessage)(nil),    // 14: gongeons.v1.ClientMessage
	(*CoreStats)(nil),        // 15: gongeons.v1.CoreStats
	(*JoinRequest)(nil),      // 16: gongeons.v1.JoinRequest
	(*ViewportCmd)(nil),      // 17: gongeons.v1.ViewportCmd
	(*MoveCmd)(nil),          // 18: gongeons.v1.MoveCmd
	(*ServerMessage)(nil),    // 19: gongeons.v1.ServerMessage
	(*JoinAccepted)(nil),     // 20: gongeons.v1.JoinAccepted
	(*Snapshot)(nil),         // 21: gongeons.v1.Snapshot
	(*Event)(nil),            // 22: gongeons.v1.Event
	(*PlayerJoined)(nil),     // 23: gongeons.v1.PlayerJoined
	(*PlayerLeft)(nil),       // 24: gongeons.v1.PlayerLeft
	(*EntityMoved)(nil),      // 25: gongeons.v1.EntityMoved
	(*IntentFailed)(nil),     // 26: gongeons.v1.IntentFailed
	(*ErrorResponse)(nil),    // 27: gongeons.v1.ErrorResponse
	nil,                      // 28: gongeons.v1.LocalizedMessage.ArgsEntry
}
var file_gongeons_proto_depIdxs = []int32{
	5,  // 0: gongeons.v1.NameParts.format:type_name -> gongeons.v1.NameFormat
	3,  // 1: gongeons.v1.Landmark.kind:type_name -> gongeons.v1.LandmarkKind
	7,  // 2: gongeons.v1.Landmark.name:type_name -> gongeons.v1.NameParts
	4,  // 3: gongeons.v1.Region.character:type_name -> gongeons.v1.RegionCharacter
	9,  // 4: gongeons.v1.Region.influence:type_name -> gongeons.v1.RegionInfluence
	7,  // 5: gongeons.v1.Region.name:type_name -> gongeons.v1.NameParts
	28, // 6: gongeons.v1.LocalizedMessage.args:type_name -> gongeons.v1.LocalizedMessage.ArgsEntry
	0,  // 7: gongeons.v1.Tile.terrain:type_name -> gongeons.v1.Terrain
	1,  // 8: gongeons.v1.Tile.occupant:type_name -> gongeons.v1.OccupantKind
	2,  // 9: gongeons.v1.Tile.structure:type_name -> gongeons.v1.Structure
	8,  // 10: gongeons.v1.Tile.landmark:type_name -> gongeons.v1.Landmark
	1,  // 11: gongeons.v1.Entity.kind:type_name -> gongeons.v1.OccupantKind
	6,  // 12: gongeons.v1.Entity.position:type_name -> gongeons.v1.Position
	16, // 13: gongeons.v1.ClientMessage.join:type_name -> gongeons.v1.JoinRequest
	18, // 14: gongeons.v1.ClientMessage.move:type_name -> gongeons.v1.MoveCmd
	17, // 15: gongeons.v1.ClientMessage.viewport:type_name -> gongeons.v1.ViewportCmd
	15, // 16: gongeons.v1.JoinRequest.stats:type_name -> gongeons.v1.CoreStats
	20, // 17: gongeons.v1.ServerMessage.accepted:type_name -> gongeons.v1.JoinAccepted
	21, // 18: gongeons.v1.ServerMessage.snapshot:type_name -> gongeons.v1.Snapshot
	22, // 19: gongeons.v1.ServerMessage.event:type_name -> gongeons.v1.Event
	27, // 20: gongeons.v1.ServerMessage.error:type_name -> gongeons.v1.ErrorResponse
	6,  // 21: gongeons.v1.JoinAccepted.spawn:type_name -> gongeons.v1.Position
	6,  // 22: gongeons.v1.Snapshot.origin:type_name -> gongeons.v1.Position
	12, // 23: gongeons.v1.Snapshot.tiles:type_name -> gongeons.v1.Tile
	13, // 24: gongeons.v1.Snapshot.entities:type_name -> gongeons.v1.Entity
	10, // 25: gongeons.v1.Snapshot.region:type_name -> gongeons.v1.Region
	23, // 26: gongeons.v1.Event.player_joined:type_name -> gongeons.v1.PlayerJoined
	24, // 27: gongeons.v1.Event.player_left:type_name -> gongeons.v1.PlayerLeft
	25, // 28: gongeons.v1.Event.entity_moved:type_name -> gongeons.v1.EntityMoved
	26, // 29: gongeons.v1.Event.intent_failed:type_name -> gongeons.v1.IntentFailed
	13, // 30: gongeons.v1.PlayerJoined.entity:type_name -> gongeons.v1.Entity
	6,  // 31: gongeons.v1.EntityMoved.from:type_name -> gongeons.v1.Position
	6,  // 32: gongeons.v1.EntityMoved.to:type_name -> gongeons.v1.Position
	14, // 33: gongeons.v1.GameService.Play:input_type -> gongeons.v1.ClientMessage
	19, // 34: gongeons.v1.GameService.Play:output_type -> gongeons.v1.ServerMessage
	34, // [34:35] is the sub-list for method output_type
	33, // [33:34] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_gongeons_proto_init() }
func file_gongeons_proto_init() {
	if File_gongeons_proto != nil {
		return
	}
	file_gongeons_proto_msgTypes[8].OneofWrappers = []any{
		(*ClientMessage_Join)(nil),
		(*ClientMessage_Move)(nil),
		(*ClientMessage_Viewport)(nil),
	}
	file_gongeons_proto_msgTypes[13].OneofWrappers = []any{
		(*ServerMessage_Accepted)(nil),
		(*ServerMessage_Snapshot)(nil),
		(*ServerMessage_Event)(nil),
		(*ServerMessage_Error)(nil),
	}
	file_gongeons_proto_msgTypes[16].OneofWrappers = []any{
		(*Event_PlayerJoined)(nil),
		(*Event_PlayerLeft)(nil),
		(*Event_EntityMoved)(nil),
		(*Event_IntentFailed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gongeons_proto_rawDesc), len(file_gongeons_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gongeons_proto_goTypes,
		DependencyIndexes: file_gongeons_proto_depIdxs,
		EnumInfos:         file_gongeons_proto_enumTypes,
		MessageInfos:      file_gongeons_proto_msgTypes,
	}.Build()
	File_gongeons_proto = out.File
	file_gongeons_proto_goTypes = nil
	file_gongeons_proto_depIdxs = nil
}
