package worldgen

import "github.com/Rioverde/gongeons/internal/game"

// Seed salts for per-layer noise decorrelation. Independent layers must see different
// underlying noise fields, otherwise elevation and temperature would look visually
// correlated across the map. XOR-ing the user seed with a fixed salt is cheap and keeps
// determinism — two runs with the same base seed produce the same per-layer seeds.
// The constants are the fractional digits of π and e in hex (Knuth-style nothing-up-my-sleeve
// numbers), so small user seeds like 0, 1, 2 cannot accidentally cancel the salt.
const (
	seedSaltTemperature int64 = 0x243f6a8885a308d3
	seedSaltMoisture    int64 = 0x13198a2e03707344
)

// temperatureOpts is a lower-frequency two-octave fBm field. Temperature varies over large
// distances (continents worth of terrain) so a bigger scale and fewer octaves feel right.
var temperatureOpts = OctaveOpts{
	Octaves:     2,
	Lacunarity:  2.0,
	Persistence: 0.5,
	Scale:       80.0,
}

// moistureOpts adds a touch more detail than temperature — rain shadows feel local — but
// still coarser than elevation.
var moistureOpts = OctaveOpts{
	Octaves:     3,
	Lacunarity:  2.0,
	Persistence: 0.5,
	Scale:       64.0,
}

// WorldGenerator is the deterministic pure function layer: given an (x, y) coordinate (or a
// whole chunk coord) it returns the tile that would live there for this seed. It owns three
// independent noise fields — elevation, temperature, moisture — sampled on global world
// coordinates so that chunk borders stitch seamlessly.
type WorldGenerator struct {
	seed        int64
	elevation   OctaveNoise
	temperature OctaveNoise
	moisture    OctaveNoise
}

// NewWorldGenerator builds the three noise fields off the supplied base seed. The per-layer
// seeds are derived by XOR-ing with fixed salts so callers that care about determinism only
// need to remember one number.
func NewWorldGenerator(seed int64) *WorldGenerator {
	return &WorldGenerator{
		seed:        seed,
		elevation:   NewOctaveNoise(seed, DefaultOctaveOpts),
		temperature: NewOctaveNoise(seed^seedSaltTemperature, temperatureOpts),
		moisture:    NewOctaveNoise(seed^seedSaltMoisture, moistureOpts),
	}
}

// Seed returns the base seed used to construct the generator. Useful for
// reproducing a world elsewhere (seed + same version of gongeons yields the
// same map).
func (g *WorldGenerator) Seed() int64 {
	return g.seed
}

// TileAt is the canonical per-coord lookup. It samples the three noise fields at the given
// global grid coordinate and hands them to the biome matrix. Same (seed, x, y) always
// yields the same tile, with or without the chunk cache in front.
func (g *WorldGenerator) TileAt(x, y int) game.Tile {
	fx, fy := float64(x), float64(y)
	elev := g.elevation.Eval2Normalized(fx, fy)
	temp := g.temperature.Eval2Normalized(fx, fy)
	moist := g.moisture.Eval2Normalized(fx, fy)
	return game.Tile{Terrain: Biome(elev, temp, moist)}
}

// Chunk fills an entire Chunk worth of tiles in a single pass: for each
// coord it calls TileAt for the base biome, then overlays the river layer.
// Biome is intentionally not altered here — river-adjacent biome blending
// is a later tuning pass. Settlements (villages, castles) are NOT placed
// at this layer — they are civilization artifacts and live on Layer 3,
// generated by the history/simulation pipeline (Phase 5 of the roadmap).
func (g *WorldGenerator) Chunk(cc ChunkCoord) Chunk {
	chunk := Chunk{Coord: cc}
	minX, _, minY, _ := cc.Bounds()

	riverTiles := g.RiverTilesInChunk(cc)

	for dy := range ChunkSize {
		for dx := range ChunkSize {
			t := g.TileAt(minX+dx, minY+dy)
			if _, wet := riverTiles[[2]int{minX + dx, minY + dy}]; wet {
				t.Overlays |= game.OverlayRiver
			}
			chunk.Tiles[dy][dx] = t
		}
	}

	return chunk
}
